Refactor GitHub Actions workflow for Playwright tests
Updated the workflow name and modified job structure for Playwright tests.

diff --git a/.github/workflows/tehtävä3.yml b/.github/workflows/tehtävä3.yml
--- a/.github/workflows/tehtävä3.yml
+++ b/.github/workflows/tehtävä3.yml
@@ -1,23 +1,34 @@
-name: Koe
+name: Playwright tests
+
 on: workflow_dispatch
 
 jobs:
-  test:
+  tests:
     runs-on: ubuntu-latest
+    container: mcr.microsoft.com/playwright:v1.63.0-noble
+    permissions:
+      contents: write
     steps:
-      - uses: actions/checkout@v7
-      - run: |
-          touch ./tests/uusi.txt
-      - uses: actions/upload-artifact@v7
-        with:
-          name: loggaus
-          path: ./log.txt
+      - name: Checkout repository
+        uses: actions/checkout@v7
+        
+      - name: Install dependencies
+        run: npm ci
 
-  another-job:
-    needs: test
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/download-artifact@v7
+      - name: Run test1
+        run: npm test -- test1 > test1.txt || true
+        
+      - name: Run test2
+        run: npm test -- test2 > test2.txt || true
+
+      - name: Upload tests to artifact
+        uses: actions/upload-artifact@v6
         with:
-          name: loggaus
-      - run: cat log.txt
+          name: Playwright test results
+          path: |
+            test1.txt
+            test2.txt
+
+      - name: Test failed
+        if: failure()
+        run: echo "Tests failed"
